name: Publish to NPM

on:
  push:
    inputs:
      releaseArgs:
        description: "Arguments to append to the release CLI command"
        required: true
        default: "--ci"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install
          npm run release -- ${{ github.event.inputs.releaseArgs }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          CI: true
